Repository IuliiaKonovalova/revolutionising-finance-hackathon, pull requests merged in 2023-01, with the labels that each got.

#17 Keiron - Create content grid in index.html
  README.md
  assets/css/styles.css
  assets/images/pexels-currency-exchange-2.webp
  assets/images/pexels-currency-exchange.jpg
  index.html
Labels: frontend

#19 keiron: Create favicon directory in images folder and render favicon
  assets/images/favicon.io/favicon.ico.png
  index.html
Labels: frontend

#24 Create Navbar component with placeholders
  assets/css/styles.css
  index.html
Labels: frontend

#29 keiron: 'Get started' button margin bug + Create Navbar Logo + Image Shadow
  assets/css/styles.css
  assets/images/logo/logo3.png
  index.html
Labels: bug, frontend

#32 Keiron: Set up footer content with links to collaborators
  index.html
Labels: frontend

#33 Reorganise github collab names in alphabetical order
  index.html
Labels: frontend

#36 Put form design into container and modify button
  index.html
Labels: frontend

#37 Various: README user stories + API google link
  README.md
  assets/css/styles.css
  assets/js/api_key_travel.js
Labels: documentation, frontend, backend

#40 Keiron: Amadeus API
  assets/css/styles.css
  assets/js/api_key_travel.js
  index.html
Labels: bug, frontend, backend

#42 keiron: Fix HTML select/option bug and create JS currency API
  assets/js/currency.js
  index.html
Labels: bug, frontend, backend

#45 Modify grid section top image with travel-related photo
  README.md
  assets/images/landing-page-photos/globe.webp
  assets/images/landing-page-photos/pexels-currency-exchange-2.webp
  assets/images/pexels-currency-exchange.jpg
  index.html
Labels: documentation, frontend

#52 Remove Latin content and fill with relevant information
  index.html
Labels: frontend

#57 Retrive currency data
  assets/js/rest_countries.js
Labels: backend

#67 keiron: Readme commit - correction and table of contents
  README.md
  assets/js/rest_countries.js
  index.html
Labels: documentation

#74 Pull Request: Fix major conflict error
  index.html
Labels: bug

#80 Keiron: PR to resolve conflictive code.
  assets/js/currency.js
  assets/js/rest_countries.js
Labels: bug

#99 keiron: readme commit: features
  README.md
  documentation/features/bottom grid.jpg
  documentation/features/currency calculator.jpg
  documentation/features/footer .jpg
  documentation/features/loading....jpg
  documentation/features/navbar.jpg
  documentation/features/search results travel api.jpg
  documentation/features/top grid.jpg
  documentation/features/travel API.jpg
Labels: documentation
